changelog:
  categories:
    - title: '🚀 Features'
      labels:
        - 'enhancement'
        - 'feat'
    - title: '🐛 Bug Fixes'
      labels:
        - 'bug'
        - 'fix'
        - 'hotfix'
    - title: '⚙️ Refactoring'
      labels:
        - 'refactor'
    - title: '🧩 UI/UX'
      labels:
        - 'UI/UX'
        - 'ui'
    - title: '📚 Documentation'
      labels:
        - 'documentation'
        - 'docs'
    - title: '🔒 Security'
      labels:
        - 'security'
    - title: '🧰 GitHub Actions'
      labels:
        - 'github_actions'
    - title: 'Other Changes'
      labels:
        - "*"
  exclude:
    labels:
      - 'skip-changelog'
      - github-actions
    authors:
      - octocat
      - renovate[bot]