name: Build Verification

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

permissions: 
  contents: read
  id-token: write 

jobs:
  generate-build-info:
    runs-on: ubuntu-latest
    outputs:
      build_info_path: ${{ steps.create-build-info.outputs.build_info_path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create build info file
        id: create-build-info
        run: |
          # Create build info file with metadata
          cat > build_info.json << EOF
          {
            "version": "${{ inputs.version }}",
            "git_commit": "${{ github.sha }}",
            "build_time": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
            "build_number": "${{ github.run_number }}",
            "github_workflow": "${{ github.workflow }}",
            "github_run_id": "${{ github.run_id }}",
            "github_run_number": "${{ github.run_number }}"
          }
          EOF
          
          echo "build_info_path=build_info.json" >> $GITHUB_OUTPUT
          cat build_info.json

      - name: Upload build info as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-info
          path: build_info.json
          