name: Create GitHub Release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      RELEASE_TOKEN:
        required: true
      GPG_PUBLIC_KEY:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Verify signed tag
        env:
          GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }} 
        run: |
          echo "Verifying tag signature for v${{ inputs.version }}..."
<<<<<<< Updated upstream
          
          # Import GPG public key
=======
          TAG_VERIFIED=false
          
          # Import GPG key if available
>>>>>>> Stashed changes
          if [ -n "$GPG_PUBLIC_KEY" ]; then
            # Write the key to a file first to avoid shell interpretation issues
            echo "$GPG_PUBLIC_KEY" > /tmp/gpg_public_key.asc
            # Fix any potential line ending issues
            sed -i 's/\r$//' /tmp/gpg_public_key.asc
<<<<<<< Updated upstream
            # Make sure the key file has proper GPG armor headers
=======
            
            # Ensure key has proper PGP headers
>>>>>>> Stashed changes
            if ! grep -q "^-----BEGIN PGP PUBLIC KEY BLOCK-----" /tmp/gpg_public_key.asc; then
              echo "Adding PGP headers to key..."
              echo "-----BEGIN PGP PUBLIC KEY BLOCK-----" > /tmp/fixed_key.asc
              cat /tmp/gpg_public_key.asc >> /tmp/fixed_key.asc
              echo "-----END PGP PUBLIC KEY BLOCK-----" >> /tmp/fixed_key.asc
              mv /tmp/fixed_key.asc /tmp/gpg_public_key.asc
            fi
<<<<<<< Updated upstream
            # Import the key from the file
            gpg --batch --import /tmp/gpg_public_key.asc || echo "::warning::Failed to import GPG key, but continuing..."
            echo "GPG Public Key import attempted."
            echo "Available GPG keys:"
            gpg --list-keys # List keys for debugging
            # Clean up
            rm -f /tmp/gpg_public_key.asc
=======
            
            # Import key with better error handling
            gpg --batch --import /tmp/gpg_public_key.asc 2>/tmp/gpg_import_error || true
            if [ -s /tmp/gpg_import_error ]; then
              echo "::warning::GPG key import had issues:"
              cat /tmp/gpg_import_error
            fi
            
            echo "GPG Public Key imported. Available GPG keys:"
            gpg --list-keys
            rm -f /tmp/gpg_public_key.asc /tmp/gpg_import_error
>>>>>>> Stashed changes
          else
            echo "::warning::GPG_PUBLIC_KEY secret not found. Will skip signature verification."
          fi
          
<<<<<<< Updated upstream
          # Check if tag exists in local repository
          if ! git tag -l "v${{ inputs.version }}" | grep -q "v${{ inputs.version }}"; then
            echo "Tag not found in local repository, attempting to fetch from remote..."
            # Fetch the specific tag without overwriting existing ones
            git fetch origin tag "v${{ inputs.version }}" --no-tags
          fi
          
          # Verify that the tag exists now
=======
          # Make sure tag exists
          if ! git tag -l "v${{ inputs.version }}" | grep -q "v${{ inputs.version }}"; then
            echo "Tag not found in local repository, attempting to fetch from remote..."
            git fetch origin tag "v${{ inputs.version }}" --no-tags || echo "Could not fetch tag from remote"
          fi
          
          # Check if tag exists
>>>>>>> Stashed changes
          if ! git tag -l "v${{ inputs.version }}" | grep -q "v${{ inputs.version }}"; then
            echo "::error::Tag v${{ inputs.version }} not found in both local and remote repositories!"
            exit 1
          fi
          
<<<<<<< Updated upstream
          # Attempt to verify the tag signature
          if git verify-tag "v${{ inputs.version }}" 2>&1 | grep -q "Good signature"; then
=======
          # Try signature verification (but don't fail if not signed)
          echo "Attempting to verify tag signature..."
          VERIFY_OUTPUT=$(git verify-tag "v${{ inputs.version }}" 2>&1) || true
          echo "Verification output: $VERIFY_OUTPUT"
          
          if echo "$VERIFY_OUTPUT" | grep -q "Good signature"; then
>>>>>>> Stashed changes
            echo "✅ Tag v${{ inputs.version }} has a valid GPG signature!"
            TAG_VERIFIED=true
          else
            echo "::warning::Tag v${{ inputs.version }} could not be verified with GPG signature."
            echo "Continuing workflow but release will be marked as unverified."
            echo "For fully verified releases, please use a GPG-signed tag:"
            echo "  git tag -s v${{ inputs.version }} -m \"Release version ${{ inputs.version }}\""
            echo "  git push origin v${{ inputs.version }}"
<<<<<<< Updated upstream
            
            # Enforce signed tags for verified releases
            exit 1
=======
>>>>>>> Stashed changes
          fi
          
          # Set verification status for later steps
          echo "tag_verified=$TAG_VERIFIED" >> $GITHUB_OUTPUT
        id: verify_tag

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts
          
      - name: List downloaded artifacts
        run: |
          echo "All downloaded artifacts:"
          find release-artifacts -type f | sort
          
          # Show specific information for the Windows installer
          WINDOWS_INSTALLER=$(find release-artifacts/windows-installer -name "*.exe" | head -1)
          if [ -n "$WINDOWS_INSTALLER" ]; then
            echo "Found Windows installer: $WINDOWS_INSTALLER"
            ls -la "$WINDOWS_INSTALLER"
          else
            echo "Warning: No Windows installer found!"
          fi

      - name: Find Windows Installer 
        id: find_installer
        run: |
          INSTALLER_PATH=$(find release-artifacts -name "MPSS_Setup_*.exe" -o -name "*.exe" | grep -i "setup" | head -1)
          if [ -z "$INSTALLER_PATH" ]; then
            INSTALLER_PATH=$(find release-artifacts -name "*.exe" | head -1)
          fi
          if [ -n "$INSTALLER_PATH" ] && [ -f "$INSTALLER_PATH" ]; then
            echo "Found installer: $INSTALLER_PATH"
            echo "path=$INSTALLER_PATH" >> $GITHUB_OUTPUT
          else
            echo "::error::Windows installer not found or not a valid file!"
            find release-artifacts -name "*.exe" || echo "No .exe files found"
            exit 1
          fi
      - name: Install cosign 
        uses: sigstore/cosign-installer@v3.4.0

      - name: Sign Windows Installer with Cosign 
        id: sign_installer
        run: |
          INSTALLER_PATH="${{ steps.find_installer.outputs.path }}"
          echo "Signing $INSTALLER_PATH..."
          cosign sign-blob --yes "$INSTALLER_PATH" --output-signature "${INSTALLER_PATH}.sig"
          echo "Signature created at ${INSTALLER_PATH}.sig"
          echo "signature_path=${INSTALLER_PATH}.sig" >> $GITHUB_OUTPUT
          
      - name: Prepare verification information 
        run: |
          # Ensure verification-artifacts directory exists
          mkdir -p verification-info
          
          # Copy verification artifacts to a directory
          cp -r release-artifacts/verification-artifacts/* verification-info/ || echo "No verification artifacts found"
          
          # Create verification readme
          cat > verification-info/README.md << EOF
          # Build Verification

          This release was built using GitHub Actions. You can verify the authenticity of this build using the information below.

          ## SHA256 Checksums

          The SHA256SUMS.txt file contains checksums for all files in this release. You can verify the checksums with:

          \`\`\`
          sha256sum -c SHA256SUMS.txt
          \`\`\`

          ## Signature Verification

          The checksums are signed using [Sigstore/cosign](https://github.com/sigstore/cosign). You can verify the signature with:

          \`\`\`
          cosign verify-blob --signature SHA256SUMS.txt.sig SHA256SUMS.txt
          \`\`\`

          ## Build Provenance

          This build was created by GitHub Actions workflow run #${{ github.run_number }} (ID: ${{ github.run_id }}).
          
          View the build: https://github.com/kavinthangavel/Media-Player-Scrobbler-for-Simkl/actions/runs/${{ github.run_id }}
          EOF

      - name: Setup GitHub CLI
        run: |
          gh --version || (
            echo "Installing GitHub CLI..."
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt update
            sudo apt install gh
          )
          
      - name: Create Release with Provenance
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          TAG_VERIFIED: ${{ steps.verify_tag.outputs.tag_verified }}
        run: |
          VERSION="${{ inputs.version }}"
          INSTALLER_PATH="${{ steps.find_installer.outputs.path }}" # Use path from previous step
          
          echo "Windows installer to upload: $INSTALLER_PATH"
          
<<<<<<< Updated upstream
          # Check if release already exists
=======
          VERIFICATION_STATUS=""
          if [ "$TAG_VERIFIED" = "true" ]; then
            VERIFICATION_STATUS="✅ This release is signed with a verified GPG key."
          else
            VERIFICATION_STATUS="⚠️ This release was not verified with a GPG signature."
          fi

>>>>>>> Stashed changes
          if gh release view "v$VERSION" &>/dev/null; then
            echo "Release v$VERSION already exists. Updating verification status and uploading artifacts."
            EXISTING_BODY=$(gh release view "v$VERSION" --json body --jq .body)
            if ! echo "$EXISTING_BODY" | grep -q "This release"; then
              NEW_BODY="$VERIFICATION_STATUS\n\n$EXISTING_BODY"
              gh release edit "v$VERSION" --notes "$NEW_BODY"
            fi
          else
<<<<<<< Updated upstream
            # Create release with provenance, attaching the main artifact directly
            gh release create "v$VERSION" \
              "$INSTALLER_PATH" \
              --title "Release $VERSION" \
              --notes "# MPSS Release $VERSION

          ## Verification
          
          This release was built using GitHub Actions workflow run #${{ github.run_number }} (ID: ${{ github.run_id }}).
          You can verify the authenticity of this build by checking the SHA256 checksums and signature files included with this release.
          
          View the build: https://github.com/kavinthangavel/Media-Player-Scrobbler-for-Simkl/actions/runs/${{ github.run_id }}" \
              --generate-notes \
              --verify-tag \
=======
            NOTES=$(cat <<EOF
$VERIFICATION_STATUS

This is release version $VERSION of Media Player Scrobbler for Simkl.

## Installation
Download the Windows installer and run it to install the application.

## Verification
See the README.md in the release assets for information on how to verify this release.
EOF
)
            gh release create "v$VERSION" \
              "$INSTALLER_PATH" \
              --title "Release $VERSION" \
              --notes "$NOTES" \
>>>>>>> Stashed changes
              --discussion-category "Releases"
            echo "Release created and Windows installer attached."
          fi
          
          # Upload verification info (checksums, checksum sig)
          echo "Uploading verification artifacts from verification-info/ ..."
          find verification-info -type f | while read file; do
            echo "Uploading $file..."
            gh release upload "v$VERSION" "$file" --clobber
          done
          
          # Upload the installer signature
          INSTALLER_SIG_PATH="${{ steps.sign_installer.outputs.signature_path }}"
          if [ -f "$INSTALLER_SIG_PATH" ]; then
            echo "Uploading installer signature: $INSTALLER_SIG_PATH"
            gh release upload "v$VERSION" "$INSTALLER_SIG_PATH" --clobber
          else
            echo "::warning:: Installer signature file not found at $INSTALLER_SIG_PATH"
          fi
          echo "Verification artifacts uploaded."
          
      - name: Delete all workflow artifacts after release
        uses: geekyeggo/delete-artifact@v5
        with:
          name: '*'      