name: Create GitHub Release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      RELEASE_TOKEN:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts
          
      - name: List downloaded artifacts
        run: find release-artifacts -type f | sort

      - name: Prepare verification information
        run: |
          # Ensure verification-artifacts directory exists
          mkdir -p verification-info
          
          # Copy verification artifacts to a directory
          cp -r release-artifacts/verification-artifacts/* verification-info/ || echo "No verification artifacts found"
          
          # Create verification readme
          cat > verification-info/README.md << EOF
          # Build Verification

          This release was built using GitHub Actions. You can verify the authenticity of this build using the information below.

          ## SHA256 Checksums

          The SHA256SUMS.txt file contains checksums for all files in this release. You can verify the checksums with:

          \`\`\`
          sha256sum -c SHA256SUMS.txt
          \`\`\`

          ## Signature Verification

          The checksums are signed using [Sigstore/cosign](https://github.com/sigstore/cosign). You can verify the signature with:

          \`\`\`
          cosign verify-blob --signature SHA256SUMS.txt.sig SHA256SUMS.txt
          \`\`\`

          ## Build Provenance

          This build was created by GitHub Actions workflow run #${{ github.run_number }} (ID: ${{ github.run_id }}).
          
          View the build: https://github.com/kavinthangavel/Media-Player-Scrobbler-for-Simkl/actions/runs/${{ github.run_id }}
          EOF
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ inputs.version }}
          name: Release ${{ inputs.version }}
          body: |
            # MPSS Release ${{ inputs.version }}
            
            ## Verification
            
            This release was built using GitHub Actions workflow run #${{ github.run_number }} (ID: ${{ github.run_id }}). 
            You can verify the authenticity of this build by checking the SHA256 checksums and signature files included with this release.
            
            View the build: https://github.com/kavinthangavel/Media-Player-Scrobbler-for-Simkl/actions/runs/${{ github.run_id }}
            
          generate_release_notes: true
          files: |
            release-artifacts/windows-installer/*.exe
            verification-info/*
          # release-artifacts/macos-installers/*.dmg
          # release-artifacts/macos-installers/*.pkg
          # release-artifacts/linux-installers/*.AppImage
          # release-artifacts/linux-installers/*.deb
          draft: false
          prerelease: false
          make_latest: true
          discussion_category_name: "Releases"
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
