name: Dependency Scanning

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays

jobs:
  dependency-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Use pip-audit instead of safety which doesn't require interactive login
        pip install pip-audit
        # Filter out Windows-specific dependencies
        sed '/pywin32/d; /pygetwindow/d' requirements.txt > requirements_linux.txt
        pip install -r requirements_linux.txt
        
    - name: Check dependencies for security vulnerabilities
      run: |
        pip-audit