name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '**.md'
      - 'simkl_scrobbler/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev
          pip install mkdocs mkdocs-material pymdown-extensions mkdocs-mermaid2-plugin
          
      - name: Setup docs directory
        run: |
          mkdir -p _site
          cp -r docs/* _site/
          # Convert GitHub-flavored markdown to standard markdown if needed
          find _site -name "*.md" -exec sed -i 's/```mermaid/\{% mermaid %\}/g; s/```$/\{% endmermaid %\}/g' {} \;
          
      - name: Build documentation
        run: |
          mkdocs build
          
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
