name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write      # Required for labeling issues
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Verify labeler config exists
      id: check_labeler_config
      run: |
        if [ -f ".github/labeler.yml" ]; then
          echo "labeler_config_exists=true" >> $GITHUB_OUTPUT
        else
          echo "labeler_config_exists=false" >> $GITHUB_OUTPUT
          echo "::warning::The .github/labeler.yml file doesn't exist. Skipping label assignment."
        fi
        
    - name: PR Labeler
      if: steps.check_labeler_config.outputs.labeler_config_exists == 'true'
      uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        sync-labels: false  # Set to false to prevent label creation attempts
        
    - name: PR Size Labeler
      uses: codelytv/pr-size-labeler@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        xs_label: 'size/xs'
        xs_max_size: '10'
        s_label: 'size/s'
        s_max_size: '100'
        m_label: 'size/m'
        m_max_size: '500'
        l_label: 'size/l'
        l_max_size: '1000'
        xl_label: 'size/xl'
        fail_if_xl: 'false'
        github_api_url: 'api.github.com'
        
    - name: Validate Conventional Commits
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        types: |
          feat
          fix
          docs
          style
          refactor
          perf
          test
          build
          ci
          chore
          revert
        requireScope: false
        wip: true
