name: Publish Python Package

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on version tags like v1.0.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use a recent Python version for building

    - name: Install Poetry
      run: pip install poetry

    - name: Build package
      run: poetry build

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      # No API token needed if using trusted publishing
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }} # Store your PyPI token as a GitHub secret