name: SIMKL Client ID Setup

on:
  workflow_dispatch:  # Manual trigger is already included here
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false
        default: 'Manual testing'
        type: string
  push:
    branches: [ main ]
    paths:
      - 'simkl_scrobbler/simkl_api.py'
      - 'simkl_scrobbler/cli.py'
  pull_request:
    branches: [ main ]
    paths:
      - 'simkl_scrobbler/simkl_api.py'
      - 'simkl_scrobbler/cli.py'
  release:
    types: [published]  # Trigger on release publication

jobs:
  inject-client-id:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Set SIMKL_CLIENT_ID
        env:
          SIMKL_CLIENT_ID: ${{ secrets.SIMKL_CLIENT_ID }}
        run: |
          echo "SIMKL_CLIENT_ID=$SIMKL_CLIENT_ID" >> $GITHUB_ENV
          
          # Verify environment variable is set
          if [ -z "$SIMKL_CLIENT_ID" ]; then
            echo "::error::SIMKL_CLIENT_ID secret is not set. Please add it to your repository secrets."
            exit 1
          fi
          
          echo "Successfully set SIMKL_CLIENT_ID environment variable"

      # Replace the placeholder in cli.py with the actual client ID
      - name: Inject Client ID into code
        run: |
          if [ -n "$SIMKL_CLIENT_ID" ]; then
            echo "Injecting SIMKL_CLIENT_ID into cli.py"
            sed -i "s/SIMKL_CLIENT_ID_PLACEHOLDER/$SIMKL_CLIENT_ID/g" simkl_scrobbler/cli.py
            echo "✅ Client ID successfully injected"
          else
            echo "❌ SIMKL_CLIENT_ID is not available in the environment"
            exit 1
          fi
          
      # Run tests to verify
      - name: Install dependencies
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --with dev --no-interaction
          
      - name: Run API tests
        run: |
          poetry run python -m unittest tests/test_simkl_api.py
          
      # Only when we're building a release
      - name: Build package with injected client ID
        if: github.event_name == 'release'
        run: |
          poetry build
          
      - name: Upload build artifacts 
        if: github.event_name == 'release'
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 7