name: Test macOS Installation

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to test'
        required: true
        default: '0.0.0'
  workflow_run:
    workflows: ["Build macOS"]
    types:
      - completed

jobs:
  test-macos-install:
    runs-on: macos-latest
    steps:
      - name: Download macOS installer artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: macos-build.yml
          workflow_conclusion: success
          name: macos-installers
          path: ./installers

      - name: List downloaded installers
        run: |
          ls -la ./installers
          echo "Downloaded installers:"
          find ./installers -type f | sort

      - name: Install DMG
        run: |
          # Find the DMG file
          DMG_FILE=$(find ./installers -name "*.dmg" | head -1)
          
          if [ -z "$DMG_FILE" ]; then
            echo "Error: No DMG file found in artifacts"
            exit 1
          fi
          
          echo "Installing from DMG: $DMG_FILE"
          
          # Mount the DMG
          VOLUME=$(hdiutil attach "$DMG_FILE" | grep Volumes | cut -f 3)
          echo "Mounted at: $VOLUME"
          
          # Find the .app in the volume
          APP_NAME=$(find "$VOLUME" -name "*.app" -maxdepth 1 | head -1)
          
          if [ -z "$APP_NAME" ]; then
            echo "Error: No .app found in DMG"
            hdiutil detach "$VOLUME"
            exit 1
          fi
          
          echo "Found app: $APP_NAME"
          
          # Copy to Applications folder
          cp -R "$APP_NAME" /Applications/
          
          # Unmount
          hdiutil detach "$VOLUME"
          
          echo "Installation complete"

      - name: Verify Installation
        run: |
          # Check if app exists in Applications
          if [ -d "/Applications/MPSS.app" ]; then
            echo "✅ Application installed successfully"
          else
            echo "❌ Application installation failed"
            exit 1
          fi
          
          # Check structure
          echo "Checking application structure..."
          ls -la "/Applications/MPSS.app/Contents/MacOS/"
          
          # Check if the executable is present
          if [ -f "/Applications/MPSS.app/Contents/MacOS/simkl-mps" ]; then
            echo "✅ Executable found"
          else
            echo "❌ Executable not found"
            exit 1
          fi
          
          # Check if the updater script exists
          if [ -f "/Applications/MPSS.app/Contents/MacOS/utils/updater.sh" ]; then
            echo "✅ Updater script found"
          else
            echo "❌ Updater script not found"
            exit 1
          fi

      - name: Run Application in Headless Mode
        run: |
          # Run with help flag to verify basic functionality
          /Applications/MPSS.app/Contents/MacOS/simkl-mps --help
          
          # Check return code
          if [ $? -eq 0 ]; then
            echo "✅ Application runs successfully in help mode"
          else
            echo "❌ Application failed to run"
            exit 1
          fi
          
          # Try version command
          /Applications/MPSS.app/Contents/MacOS/simkl-mps --version
          
          # Run status command
          /Applications/MPSS.app/Contents/MacOS/simkl-mps status

      - name: Cleanup
        run: |
          # Remove the application
          rm -rf "/Applications/MPSS.app"
          echo "Application removed"